apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "steam-game-server.fullname" . }}-config
  labels:
    {{- include "steam-game-server.labels" . | nindent 4 }}
data:
  {{- range $configName, $configData := .Values.serverConfigs }}
  {{ $configData.filename }}: |
    {{- $configData.content | nindent 4 }}
  {{- end }}
