apiVersion: v1
kind: Service
metadata:
  name: {{ include "steam-game-server.fullname" . }}
  labels:
    {{- include "steam-game-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: UDP
      name: game
  selector:
    {{- include "steam-game-server.selectorLabels" . | nindent 4 }}
